#!/usr/bin/env python3
"""Inject build version info into the Tools UI as a generated JS file.

Reads the version from the repo root version file and writes a build-info.js
file into the tools _common/js/ directory.

This file is a CI-generated artifact — it should NOT be committed to git.
Components read window.SGRAPH_BUILD to display version info.

Usage:
    python scripts/inject_build_version.py
    python scripts/inject_build_version.py --version v0.1.0
    python scripts/inject_build_version.py --dry-run
"""

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT        = Path(__file__).parent.parent
VERSION_FILE     = REPO_ROOT / 'sgraph_ai_tools' / 'version'
UI_BASE          = 'sgraph_ai_tools__static/tools'

BUILD_INFO_TEMPLATE = """\
/* Generated by CI — do not edit manually.
   Source: scripts/inject_build_version.py
   Build:  {build_time} */
window.SGRAPH_BUILD = {{
    version   : '{version}',
    buildTime : '{build_time}'
}};
"""


def version_to_ifd_path(version):
    clean = version.lstrip('v')
    parts = clean.split('.')
    if len(parts) == 3:
        major, minor, patch = parts
        return f'v{major}/v{major}.{minor}/v{major}.{minor}.{patch}'
    return version


def main():
    parser = argparse.ArgumentParser(description='Inject build version into Tools UI')
    parser.add_argument('--version', type=str, default=None,
                        help='Version to target (default: read from version file)')
    parser.add_argument('--dry-run', action='store_true',
                        help='Print what would be written without writing')
    args = parser.parse_args()

    # Read version
    version = args.version
    if not version:
        if not VERSION_FILE.exists():
            print(f"ERROR: Version file not found: {VERSION_FILE}")
            return 1
        version = VERSION_FILE.read_text().strip()

    # Resolve target path
    ifd_path    = version_to_ifd_path(version)
    ui_base     = REPO_ROOT / UI_BASE
    version_dir = ui_base / ifd_path
    target      = version_dir / '_common' / 'js' / 'build-info.js'

    # Build timestamp
    build_time = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

    # Generate content
    content = BUILD_INFO_TEMPLATE.format(
        version=version,
        build_time=build_time,
    )

    print(f"SGraph Tools — Build Version Injection")
    print(f"  Version    : {version}")
    print(f"  Build time : {build_time}")
    print(f"  Target     : {target}")

    if args.dry_run:
        print(f"\n[dry-run] Would write:\n{content}")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')
    print(f"\n  Written: {target}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
