#!/bin/bash
# ---------------------------------------------------------------------------
# Local dev server for tools.sgraph.ai
#
# In production, the CI deploy script flattens the versioned IFD structure:
#   tools/v0/v0.1/v0.1.4/en-gb/   →  latest/en-gb/
#   tools/v0/v0.1/v0.1.4/_common/  →  latest/_common/
#   core/                           →  latest/core/
#   components/                     →  latest/components/
#
# IFD principle: each version only contains its DELTAS (new/changed files).
# The final served state is the layering of ALL versions in order, with
# later versions overwriting earlier ones:
#   v0.1.0 (base) → v0.1.1 (overlay) → v0.1.2 → ... → v0.1.5 (latest)
#
# This script replicates that locally by copying each version in order
# into a temporary directory that mirrors the production URL structure.
# ---------------------------------------------------------------------------

PORT=10063
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
STATIC_DIR="$REPO_ROOT/sgraph_ai_tools__static"
# Auto-detect latest IFD version from directory structure
UI_VERSION=$(ls -d "$REPO_ROOT/sgraph_ai_tools__static/tools/v0/v0.1"/v0.1.* 2>/dev/null | sort -V | tail -1 | xargs basename)
IFD_BASE="tools/v0/v0.1"
SERVE_DIR="$REPO_ROOT/.local-server"

# Clean up on exit
cleanup() {
    echo ""
    echo "Stopping server..."
    rm -rf "$SERVE_DIR"
}
trap cleanup EXIT

# Build the local serve directory by layering IFD versions
echo "Building local server directory (IFD version layering)..."
rm -rf "$SERVE_DIR"
mkdir -p "$SERVE_DIR"

# Layer all patch versions in order: v0.1.0, v0.1.1, ..., v0.1.5
# Each version's content overwrites the previous, so only deltas are needed per version
echo "  Layering IFD versions from $IFD_BASE/:"
for version_dir in $(ls -d "$STATIC_DIR/$IFD_BASE"/v0.1.* 2>/dev/null | sort -V); do
    version_name=$(basename "$version_dir")
    echo "    + $version_name"

    # Copy locale folders (en-gb/, etc.) — merge contents, don't nest
    for sub in "$version_dir"/*/; do
        dirname=$(basename "$sub")
        if [ "$dirname" != "_common" ] && [ "$dirname" != "i18n" ] && [ -d "$sub" ]; then
            mkdir -p "$SERVE_DIR/$dirname"
            cp -r "$sub"/* "$SERVE_DIR/$dirname/" 2>/dev/null || true
        fi
    done

    # Copy _common/ — merge contents into existing dir
    if [ -d "$version_dir/_common" ]; then
        mkdir -p "$SERVE_DIR/_common"
        cp -r "$version_dir/_common"/* "$SERVE_DIR/_common/" 2>/dev/null || true
    fi

    # Copy root files (404.html, manifest.json, etc.)
    for f in "$version_dir"/*.html "$version_dir"/*.json "$version_dir"/*.txt "$version_dir"/*.xml; do
        [ -f "$f" ] && [ "$(basename "$f")" != "index.html" ] && cp "$f" "$SERVE_DIR/$(basename "$f")"
    done
done

# Symlink core/ and components/ from static root
[ -d "$STATIC_DIR/core" ]       && ln -sf "$STATIC_DIR/core"       "$SERVE_DIR/core"
[ -d "$STATIC_DIR/components" ] && ln -sf "$STATIC_DIR/components" "$SERVE_DIR/components"

# Symlink tests/
[ -d "$STATIC_DIR/tests" ]      && ln -sf "$STATIC_DIR/tests"      "$SERVE_DIR/tests"

# Inject build-info.js for local dev (CI generates this in production)
mkdir -p "$SERVE_DIR/_common/js"
cat > "$SERVE_DIR/_common/js/build-info.js" <<JSEOF
/* Generated by run-locally.sh — local development only */
window.SGRAPH_BUILD = {
    appVersion : 'local-dev',
    uiVersion  : '$UI_VERSION',
    buildTime  : '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
};
JSEOF

# Create a root index.html that redirects to /en-gb/
cat > "$SERVE_DIR/index.html" <<'HTMLEOF'
<!DOCTYPE html>
<html>
<head><meta http-equiv="refresh" content="0;url=/en-gb/"></head>
<body><a href="/en-gb/">Redirecting to /en-gb/...</a></body>
</html>
HTMLEOF

echo ""
echo "Starting tools.sgraph.ai local server..."
echo "  Root:       $SERVE_DIR"
echo "  IFD base:   $STATIC_DIR/$IFD_BASE"
echo "  Latest:     $UI_VERSION"
echo ""
echo "  Layered content:"
echo "    Tools:  $(ls "$SERVE_DIR/en-gb/" 2>/dev/null | grep -v index.html | tr '\n' ' ')"
echo ""
echo "  URLs:"
echo "    Home:           http://localhost:$PORT/"
echo "    Tools:          http://localhost:$PORT/en-gb/"
echo "    Image Tools:    http://localhost:$PORT/en-gb/image-tools/"
echo "    Video Tools:    http://localhost:$PORT/en-gb/video-tools/"
echo "    Vault Browser:  http://localhost:$PORT/en-gb/vault-browser/"
echo "    Tests:          http://localhost:$PORT/tests/"
echo ""

python3 -m http.server $PORT --directory "$SERVE_DIR"
