#!/bin/bash
# ---------------------------------------------------------------------------
# Local dev server for tools.sgraph.ai
#
# In production, the CI deploy script flattens the versioned IFD structure:
#   tools/v0/v0.1/v0.1.4/en-gb/   →  latest/en-gb/
#   tools/v0/v0.1/v0.1.4/_common/  →  latest/_common/
#   core/                           →  latest/core/
#   components/                     →  latest/components/
#
# This script replicates that locally by creating symlinks in a temporary
# directory that mirrors the production URL structure.
# ---------------------------------------------------------------------------

PORT=10063
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
STATIC_DIR="$REPO_ROOT/sgraph_ai_tools__static"
UI_VERSION="v0.1.4"
IFD_PATH="tools/v0/v0.1/$UI_VERSION"
SERVE_DIR="$REPO_ROOT/.local-server"

# Clean up on exit
cleanup() {
    echo ""
    echo "Stopping server..."
    rm -rf "$SERVE_DIR"
}
trap cleanup EXIT

# Build the local serve directory with symlinks
echo "Building local server directory (mirroring production URL structure)..."
rm -rf "$SERVE_DIR"
mkdir -p "$SERVE_DIR"

# Versioned content → root (en-gb/, _common/, 404.html, etc.)
CONTENT_DIR="$STATIC_DIR/$IFD_PATH"
if [ ! -d "$CONTENT_DIR" ]; then
    echo "ERROR: Content directory not found: $CONTENT_DIR"
    exit 1
fi

# Symlink locale folders (en-gb/, etc.)
for locale_dir in "$CONTENT_DIR"/*/; do
    dirname=$(basename "$locale_dir")
    if [ "$dirname" != "_common" ] && [ -d "$locale_dir" ]; then
        ln -sf "$locale_dir" "$SERVE_DIR/$dirname"
    fi
done

# Copy _common (not symlink) so we can inject build-info.js
cp -r "$CONTENT_DIR/_common" "$SERVE_DIR/_common"

# Symlink core/ and components/ from static root
[ -d "$STATIC_DIR/core" ]       && ln -sf "$STATIC_DIR/core"       "$SERVE_DIR/core"
[ -d "$STATIC_DIR/components" ] && ln -sf "$STATIC_DIR/components" "$SERVE_DIR/components"

# Symlink tests/
[ -d "$STATIC_DIR/tests" ]      && ln -sf "$STATIC_DIR/tests"      "$SERVE_DIR/tests"

# Copy root files (404.html, manifest.json, etc.) — skip index.html, we create our own
for f in "$CONTENT_DIR"/*.html "$CONTENT_DIR"/*.json; do
    [ -f "$f" ] && [ "$(basename "$f")" != "index.html" ] && cp "$f" "$SERVE_DIR/$(basename "$f")"
done

# Inject build-info.js for local dev (CI generates this in production)
mkdir -p "$SERVE_DIR/_common/js"
cat > "$SERVE_DIR/_common/js/build-info.js" <<JSEOF
/* Generated by run-locally.sh — local development only */
window.SGRAPH_BUILD = {
    appVersion : 'local-dev',
    uiVersion  : '$UI_VERSION',
    buildTime  : '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
};
JSEOF

# Create a root index.html that redirects to /en-gb/
cat > "$SERVE_DIR/index.html" <<'HTMLEOF'
<!DOCTYPE html>
<html>
<head><meta http-equiv="refresh" content="0;url=/en-gb/"></head>
<body><a href="/en-gb/">Redirecting to /en-gb/...</a></body>
</html>
HTMLEOF

echo ""
echo "Starting tools.sgraph.ai local server..."
echo "  Root:       $SERVE_DIR"
echo "  Content:    $CONTENT_DIR"
echo ""
echo "  URLs:"
echo "    Home:           http://localhost:$PORT/"
echo "    Tools:          http://localhost:$PORT/en-gb/"
echo "    Vault Browser:  http://localhost:$PORT/en-gb/vault-browser/"
echo "    Vault Pyodide:  http://localhost:$PORT/en-gb/vault-pyodide/"
echo "    Tests:          http://localhost:$PORT/tests/"
echo ""

python3 -m http.server $PORT --directory "$SERVE_DIR"
